In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

#For reproducibility
torch. manual_seed(1)

x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape)

print('e^1 equals: ', torch.exp(torch.FloatTensor([1])))

W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
print(hypothesis)
print(hypothesis.shape)

#print('1/(1+e^{-1}) equals: ', torch.sigmoid(torch.FloatTensor([1])))
#hypothesis = torch.sigmoid(x_train.matmul(W)+b)
#print(hypothesis)
#print(hypothesis.shape)

#print(hypothesis)
#print(y_train)

#-(y_train[0] * torch.log(hypothesis[0]) +
 #   (1-y_train[0]) * torch.log(1-hypothesis[0]))  #ylog(H(x))+(1-y)(log(1-H(x)))

losses = -(y_train * torch.log(hypothesis) +
            (1-y_train) * torch.log(1 - hypothesis))  #ylog(H(x))+(1-y)(log(1-H(x)))
print(losses)    

cost = losses.mean()
print(cost)
    

torch.Size([6, 2])
torch.Size([6, 1])
e^1 equals:  tensor([2.7183])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])
tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)
tensor(0.6931, grad_fn=<MeanBackward0>)


In [21]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

Whole Training Procedure

In [31]:
#모델초기화
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
#optimizer 설정
optimizer = optim.SGD([W,b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    #cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W)+b)
    cost = F.binary_cross_entropy(hypothesis,y_train)

    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:6d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

hypothesis = torch.sigmoid(x_train.matmul(W)+b)
print(hypothesis[:5]) 


Epoch      0/1000 Cost: 0.693147
Epoch    100/1000 Cost: 0.134722
Epoch    200/1000 Cost: 0.080643
Epoch    300/1000 Cost: 0.057900
Epoch    400/1000 Cost: 0.045300
Epoch    500/1000 Cost: 0.037261
Epoch    600/1000 Cost: 0.031673
Epoch    700/1000 Cost: 0.027556
Epoch    800/1000 Cost: 0.024394
Epoch    900/1000 Cost: 0.021888
Epoch   1000/1000 Cost: 0.019852
tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01]], grad_fn=<SliceBackward0>)


Evaluation

In [47]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5].type(torch.uint8))

tensor([[0],
        [0],
        [0],
        [1],
        [1]], dtype=torch.uint8)
